apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
data:
  DB_NAME: "mydatabase"
  DB_USERNAME: "myuser"
  DB_HOST: 10.100.163.136
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  db_password: bXlwYXNzd29yZA==